sudo: required
language: go
go:
- 1.11
script:
- env GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
after_success:
- curl -sL https://codecov.io/bash | bash
- bash -l ./release.sh